### ISSUE TITLE
Bug in "activities.py add": if you provide TR version of spec, you get "TypeError: 'BetterUrl' object is not subscriptable"

### ISSUE THREAD

**Issue by dholbert** [mozilla/standards-positions#655]
STR:
1. In a clone of this repo, run:  `python ./activities.py add  https://www.w3.org/TR/css-contain-3/`
(note this the URL I'm giving here is for the official TR version of the spec, not the editor's draft)

ACTUAL RESULTS:
```
Traceback (most recent call last):
  File "/scratch/work/builds/standards-positions/./activities.py", line 290, in fetch_spec_data
    spec_data = self.parser().parse(soup, url)
  File "/scratch/work/builds/standards-positions/./activities.py", line 416, in parse
    raise BetterUrl(ed_url)
__main__.BetterUrl: https://drafts.csswg.org/css-contain-3/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/work/builds/standards-positions/./activities.py", line 607, in <module>
    ENTRY = SpecEntry(SPEC_URL)
  File "/scratch/work/builds/standards-positions/./activities.py", line 257, in __init__
    new_entry = self.fetch_spec_data(spec_url)
  File "/scratch/work/builds/standards-positions/./activities.py", line 292, in fetch_spec_data
    new_url = why[0]
TypeError: 'BetterUrl' object is not subscriptable
```

EXPECTED RESULTS:
The script should properly replace (or alert me of) its suggested better-URL (the editor's draft in this case) without throwing exceptions-on-top-of-exceptions. :)

**Comment by zcorpan** [comment]
No longer relevant, see https://github.com/mozilla/standards-positions/pull/1063.
